export const FETCH_USER_GOOGLE = 'FETCH_USER_GOOGLE';
export const FETCH_USER_SPOTIFY = 'FETCH_USER_SPOTIFY';
export const FETCH_USERS_BLOG = 'FETCH_USERS_BLOG';
export const FETCH_POSTS_BLOG = 'FETCH_POSTS_BLOG';